Limit EG to a single GatewayClass
envoyproxy/gateway pull request #109
Opened 2022-06-14 20:35 UTC by arkodg

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

2022-06-15 16:57 UTC, danehans requested changes
1 nit, otherwise lgtm.

2022-06-15 16:57 UTC, danehans commented on docs/design/SYSTEM_DESIGN.md
> +* Each Envoy Gateway will consume one [GatewayClass resources](https://gateway-api.sigs.k8s.io/concepts/api-overview/#gatewayclass) to manage a unique fleet of Envoy Proxies.
s/resources/resource/

2022-06-17 15:37 UTC, alexgervais approved these changes

2022-06-17 18:07 UTC, danehans approved these changes

2022-06-17 18:07 UTC, merged