ci: support automation helm chart release
envoyproxy/gateway pull request #1092
Opened 2023-03-01 09:50 UTC by Xunzhuo

Resolves: #1090 

After: #1091

2023-03-01 16:15 UTC, haq204 approved these changes
lgtm

2023-03-02 16:43 UTC, AliceProxy approved these changes

2023-03-03 02:10 UTC, zirain requested changes
/hold

IMO, it's not a good idea adding chart as part of Github release artifacts. 
Hold this before we make a decision about using of OCI.

2023-03-03 02:12 UTC, Xunzhuo commented
Right, I am thinking use OCI too. I will update the PRs.

2023-03-08 06:44 UTC, zirain commented
```
helm package charts/eg/
helm push eg-0.1.0.tgz oci://docker.io/envoy
```

helm install eg oci://docker.io/envoy/eg --version 0.1.0

2023-03-08 21:30 UTC, arkodg commented
sidenote @Xunzhuo  why is the chart called `eg` and not `envoy-gateway` ?

2023-03-09 03:56 UTC, Xunzhuo commented
@arkodg This can be changed since we haven`t release helm yet. Any ideas which is better?

2023-03-09 21:49 UTC, arkodg commented on .github/workflows/latest_release.yaml
> +          We use `0.0.0` as the latest chart version to install latest envoy-gateway:
is this common convention used elsewhere ?

2023-03-09 21:53 UTC, arkodg commented on tools/make/image.mk
> +OCI_REGISTRY ?= oci://docker.io/envoyproxy
can we add these to `helm.mk` ?

2023-03-09 21:53 UTC, arkodg commented on tools/make/image.mk
> +CHART_VERSION ?= 0.1.0
should this be `$(REV)` instead of defaulting to 0.1.0 ?

2023-03-09 21:55 UTC, arkodg commented on tools/make/image.mk
> +OCI_REGISTRY ?= oci://docker.io/envoyproxy
or `kube.mk`

2023-03-13 03:08 UTC, zirain approved these changes
LGTM

2023-03-13 03:09 UTC, merged