ci: don't run build & test for docs in CI
envoyproxy/gateway pull request #1186
Opened 2023-03-19 04:00 UTC by muyuan0

Fix #1159

I find a way to skip the tests when the change is doc only, with minimal change on the current workflow.

The effect of doc only change can be seen at https://github.com/muyuan0/gateway/pull/3/
The effect of doc&code change can be seen at https://github.com/muyuan0/gateway/pull/4/

And now the push event will trigger the coverage-test whether it is doc only change or not.

2023-03-21 02:44 UTC, zirain commented
cc @Xunzhuo

2023-03-21 19:54 UTC, arkodg commented
im a -1 on this change atm, we are adding complexity (running an extra user based GH and adding checks) to ensure that we dont run tests (which adds a few more min of GH runner time), and I would prefer to keep things simple rn.

2023-03-21 21:44 UTC, kflynn requested changes
I'm not sure if this change will cause `build` (which depends on `coverage-test`) to be skipped, or to fail -- has that been checked? 🙂

2023-03-23 07:39 UTC, muyuan0 commented
> I'm not sure if this change will cause `build` (which depends on `coverage-test`) to be skipped, or to fail -- has that been checked? 🙂

It will be skipped, you can see the output of https://github.com/muyuan0/gateway/pull/3

2023-03-23 07:50 UTC, muyuan0 commented
> im a -1 on this change atm, we are adding complexity (running an extra user based GH and adding checks) to ensure that we dont run tests (which adds a few more min of GH runner time), and I would prefer to keep things simple rn.

What about keeping it open in case it's in need in the future?

2023-03-23 19:56 UTC, arkodg commented
> > im a -1 on this change atm, we are adding complexity (running an extra user based GH and adding checks) to ensure that we dont run tests (which adds a few more min of GH runner time), and I would prefer to keep things simple rn.
> 
> What about keeping it open in case it's in need in the future?

sure, sgtm

2023-05-09 21:41 UTC, AliceProxy commented
We're going to close this one for now but if this is desired in the future then we can re-open.

2023-05-09 21:41 UTC, closed without merging

2023-05-09 21:41 UTC, kflynn commented
Thanks much for working on this!