gateway: set up fullpath log format
envoyproxy/gateway pull request #1237
Opened 2023-03-30 15:11 UTC by cnvergence

fixes: https://github.com/envoyproxy/gateway/issues/1216

2023-03-31 16:55 UTC, arkodg commented
> hey @cnvergence can you post what the logs looked like before and after, TIA !

(they should probably be available in CI logs)

2023-03-31 18:08 UTC, cnvergence commented
Sure, @arkodg 
Logs were looking like this before:
```bash
envoy-gateway-6df79575c5-4f7cd envoy-gateway 2023-03-31T18:03:56.308Z	INFO	controller/controller.go:228	Starting workers	{"runner": "provider", "controller": "gatewayapi", "worker count": 1}
envoy-gateway-6df79575c5-4f7cd envoy-gateway 2023-03-31T18:03:56.559Z	INFO	runner/runner.go:51	started	{"runner": "infrastructure"}
envoy-gateway-6df79575c5-4f7cd envoy-gateway 2023-03-31T18:03:56.560Z	INFO	runner/runner.go:183	loaded TLS certificate and key	{"runner": "xds-server"}
envoy-gateway-6df79575c5-4f7cd envoy-gateway 2023-03-31T18:03:56.560Z	INFO	runner/runner.go:88	started	{"runner": "xds-server"}
```
With FullCallerEncoder logs are looking like this:
```bash
envoy-gateway-6df79575c5-zrp8m envoy-gateway 2023-03-31T17:59:33.410Z	INFO	/Users/user/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:228	Starting workers	{"runner": "provider", "controller": "gatewayapi", "worker count": 1}
envoy-gateway-6df79575c5-zrp8m envoy-gateway 2023-03-31T17:59:33.661Z	INFO	/Users/user/go/src/github.com/envoyproxy/gateway/internal/infrastructure/runner/runner.go:51	started	{"runner": "infrastructure"}
envoy-gateway-6df79575c5-zrp8m envoy-gateway 2023-03-31T17:59:33.661Z	INFO	/Users/user/go/src/github.com/envoyproxy/gateway/internal/xds/server/runner/runner.go:183	loaded TLS certificate and key{"runner": "xds-server"}
envoy-gateway-6df79575c5-zrp8m envoy-gateway 2023-03-31T17:59:33.661Z	INFO	/Users/user/go/src/github.com/envoyproxy/gateway/internal/xds/server/runner/runner.go:88	started	{"runner": "xds-server"}
```

2023-04-01 06:33 UTC, zirain commented on internal/log/log.go
> +	}
```suggestion
	zapConfig := zap.NewDevelopmentConfig()
        zapConfig.EncoderConfig.EncodeCaller = zapcore.FullCallerEncoder
```

2023-04-01 06:34 UTC, zirain reviewed
No strong option, should make this with a feature gate?

2023-04-03 10:50 UTC, cnvergence commented
> No strong option, should make this with a feature gate?

That's a good idea, if the long paths will make it harder to read through logs.

2023-04-04 07:39 UTC, misstick86 commented
@arkodg sorry, I don't describe this issue clearly.  I also don't think setup fullpath is good idea. like i said the original issue. it's too long and not suitable to read. if we want set relative path may be it's necessary to  customize `zap caller`. or we can open this issue and wait for `zap` package support relative path setting.  somebody has other idea just comment on below.

2023-04-04 21:35 UTC, kflynn requested changes
This should be configurable, not forced for everyone, I think.

2023-04-07 17:42 UTC, kflynn commented
Closing since we're also closing #1216.

2023-04-07 17:42 UTC, closed without merging