fix: mergeGateways panics when restarting control plane
envoyproxy/gateway pull request #2283
Opened 2023-12-08 03:29 UTC by Xunzhuo

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/envoyproxy/gateway/issues/2282

2023-12-08 04:19 UTC, zirain commented
can you add a (e2e)test for this to avoid regression in the future?

2023-12-08 04:50 UTC, Xunzhuo commented
Can this be a follow up ? @zirain

2023-12-08 07:30 UTC, Xunzhuo commented
Okay, let me update it later

2023-12-13 04:06 UTC, Xunzhuo commented
I still think we can start working on e2e after https://github.com/envoyproxy/gateway/issues/2029#issuecomment-1808623065

let us fix the bug first @zirain

2023-12-13 04:26 UTC, zirain approved these changes

2023-12-13 04:54 UTC, zzjin commented on internal/provider/kubernetes/predicates.go
> +			return false
If return false here, the service here(and deploy below) will always return false, witch means the `MergeGateways` do not work anymore.

2023-12-13 07:17 UTC, Xunzhuo commented
Let me double check it before merging it.

2023-12-13 12:28 UTC, cnvergence requested changes
@Xunzhuo ptal

2023-12-13 12:28 UTC, cnvergence commented on internal/provider/kubernetes/predicates.go
>  			r.statusUpdateForGateway(ctx, gw)
```suggestion
		}
	if res != nil && len(res.Gateways) > 0 {
		for _, gw := range res.Gateways {
			gw := gw
			r.statusUpdateForGateway(ctx, gw)
			}
		}
```

2023-12-13 12:28 UTC, cnvergence commented on internal/provider/kubernetes/predicates.go
>  			r.statusUpdateForGateway(ctx, gtw)
```suggestion
		}
	if res != nil && len(res.Gateways) > 0 {
		for _, gw := range res.Gateways {
			gw := gw
			r.statusUpdateForGateway(ctx, gw)
			}
		}
```

2023-12-13 12:28 UTC, cnvergence commented on internal/provider/kubernetes/predicates.go
>  			r.statusUpdateForGateway(ctx, gw)
we will need to add this check

2023-12-13 12:41 UTC, cnvergence commented on internal/provider/kubernetes/predicates.go
> +		}
suggestion missed that
```suggestion

```

2023-12-13 12:41 UTC, cnvergence commented on internal/provider/kubernetes/predicates.go
>  		}
```suggestion
```

2023-12-13 12:41 UTC, cnvergence commented on internal/provider/kubernetes/predicates.go
>  		}
same

2023-12-13 12:44 UTC, cnvergence approved these changes

2023-12-13 12:47 UTC, cnvergence approved these changes
lgtm now

2023-12-13 13:29 UTC, zirain approved these changes

2023-12-13 13:30 UTC, merged