fix Envoy Fails to Add Router
envoyproxy/gateway pull request #274
Opened 2022-08-29 07:47 UTC by zirain

fixes: #272 
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>

2022-08-29 16:47 UTC, danehans requested changes
@zirain I am still seeing the same #272 issue with this PR:

## Envoy Gateway Logs
```
2022-08-29T16:43:11.320Z	INFO	cache/logrwrapper.go:24	nodeID "envoy-eg-6f568884ff-6f4gx" requested type.googleapis.com/envoy.config.listener.v3.Listener[] and known map[]. Diff []	{"runner": "xds-server"}
2022-08-29T16:43:11.320Z	INFO	cache/logrwrapper.go:24	respond type.googleapis.com/envoy.config.listener.v3.Listener[] version "" with version "1"	{"runner": "xds-server"}
2022-08-29T16:43:11.320Z	INFO	cache/logrwrapper.go:24	Sending Response on stream 3 to node envoy-eg-6f568884ff-6f4gx	{"runner": "xds-server"}
```

## Envoy Logs
```
[2022-08-29 16:43:10.292][1][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) listener_default-eg-http_8080: Didn't find a registered implementation for 'envoy.filters.http.router' with type URL: ''
```

The [failed CI run](https://github.com/envoyproxy/gateway/runs/8065947972?check_suite_focus=true) supports these findings.

2022-08-29 16:47 UTC, danehans commented on internal/xds/translator/testdata/in/xds-ir/empty-hostnames.yaml
> +  - name: "first-route"
Remove whitespace.

2022-08-29 16:57 UTC, arkodg commented on internal/xds/translator/translator.go
> +		if len(vHost.Domains) == 0 {
afaik this shouldnt be needed here, the Gateway API translator should have set this to `*` while creating the IR
https://github.com/envoyproxy/gateway/blob/a4773ec06b675cc4a6ee1220d0c8ece09053471c/internal/ir/xds.go#L84

2022-08-29 17:01 UTC, danehans commented
FYI @zirain @arkodg I do not see this issue when I create an HTTPRoute that includes a `hostname`. FOr example:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
  - name: eg
  hostnames:
  - "*.example.com"
  rules:
  - backendRefs:
    - name: httpbin
      port: 80
```

2022-08-29 17:28 UTC, arkodg commented on internal/xds/translator/translator.go
> +		if len(vHost.Domains) == 0 {
looks like `Validate` is not called today, will raise a PR once https://github.com/envoyproxy/gateway/pull/216 is in to call Validate before performing a `Store`

2022-08-29 18:21 UTC, arkodg commented on internal/xds/translator/translator.go
> +		if len(vHost.Domains) == 0 {
raised https://github.com/envoyproxy/gateway/pull/276

2022-08-30 01:01 UTC, zirain commented
@danehans I face this issue with the yaml files your provider [here](https://github.com/envoyproxy/gateway/issues/267#issue-1352727798)

I'm OK to close this PR, which is a kind of `defensive programming`.

2022-08-30 08:15 UTC, zirain commented
still face this with https://github.com/envoyproxy/gateway/pull/276 https://github.com/envoyproxy/gateway/pull/264 https://github.com/envoyproxy/gateway/pull/269

```
[2022-08-30 08:10:30.712][1][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.Domains: value must contain at least 1 item(s)): name: "route_default-eg-http"
virtual_hosts {
  name: "route_default-eg-http"
  routes {
    match {
      prefix: "/"
      headers {
        name: ":authority"
        string_match {
          exact: "*.example.com"
        }
      }
    }
    route {
      cluster: "cluster_default-httpbin-rule-0-match-0-*.example.com"
    }
  }
}
```

2022-08-30 08:50 UTC, zirain commented
replaced by https://github.com/envoyproxy/gateway/pull/286

2022-08-30 08:50 UTC, closed without merging