fix: ReplaceFullPath not working for root path (/)
envoyproxy/gateway pull request #2817
Opened 2024-03-07 08:31 UTC by eternalphane

**What type of PR is this?**

**What this PR does / why we need it**:
`ReplaceFullPath` should support replacing root path during rewriting/redirecting.

**Which issue(s) this PR fixes**:

2024-03-07 11:14 UTC, zirain requested changes
In case this happen, please kindly add an e2e test.

2024-03-08 00:22 UTC, arkodg commented
@eternalphane can you share the config that not working ?
would be good to compare it with expectations from the spec https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPPathModifier

2024-03-08 02:07 UTC, eternalphane commented
@arkodg [This simple example](https://github.com/kubernetes-sigs/gateway-api/blob/main/examples/standard/http-rewrite.yam) is not working when accessing the root path:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-1
  namespace: gateway-api-example-ns1
spec:
  parentRefs:
  - name: my-filter-gateway
    sectionName: http
  hostnames:
  - my-filter.example.com
  rules:
  - filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /foo
```

2024-03-08 02:11 UTC, arkodg commented
@eternalphane is the request to my-filter.example.com  or my-filter.example.com/

2024-03-08 04:15 UTC, eternalphane commented
> is the request to my-filter.example.com or my-filter.example.com/

Both seem to be the same 😂
![image](https://github.com/envoyproxy/gateway/assets/11267872/fa39d900-c032-4672-a74d-8e70cb582c01)

2024-04-10 10:27 UTC, arkodg commented on internal/xds/translator/route.go
> +					Regex: "/.*",
hey sorry for the delay here, lets tighten this up a bit with `^/.*$`

so something random like `blah/` doesnt get accepted

2024-06-05 20:38 UTC, arkodg commented
closed in favor of https://github.com/envoyproxy/gateway/pull/3530

2024-06-05 20:38 UTC, closed without merging