Adds Kind Host-to-Container Port Mapping
envoyproxy/gateway pull request #285
Opened 2022-08-30 01:42 UTC by danehans

Maps host port 9080 to container port 80 and host port 9443 to container port 443 for kind cluster.

Fixes: #284 

Signed-off-by: danehans <daneyonhansen@gmail.com>

2022-08-30 20:01 UTC, danehans commented
@skriss PTAL when you have a moment. We need this for RC1.

2022-09-06 17:05 UTC, skriss commented on tools/hack/kind-expose-ports.yaml
> +        hostPort: 9080
The conformance tests send requests to whatever address is in the Gateway's status.addresses field. It needs to be routable from wherever the conformance tests are run.

xref. #330

2022-09-06 21:04 UTC, LukeShu commented on tools/hack/create-cluster.sh
> +readonly CONFIG_FILE="${REPO}/tools/hack/kind-expose-ports.yaml"
Ugh, I hate that these types of hacks are necessary.  We solved this long ago with `realpath`, but macOS is holding the world back...

But wait, we have `git`!
```bash
REPO=$(git rev-parse --show-toplevel)
```

2022-09-08 17:04 UTC, LukeShu requested changes

2022-09-08 17:04 UTC, LukeShu commented on tools/hack/kind-expose-ports.yaml
> +  - role: control-plane
Please rebase/merge with `main`; the yamllint config is going to complain about this whitespace.

2022-09-08 23:15 UTC, danehans commented
I am closing this issue since this functionality is not required for conformance tests and metallb does not work with Mac, [xref](https://kind.sigs.k8s.io/docs/user/loadbalancer/).

2022-09-08 23:15 UTC, closed without merging