Adds Make Target to Generate Release Manifests
envoyproxy/gateway pull request #300
Opened 2022-08-30 23:54 UTC by danehans

Adds a Make target to generate:

1. The Kube manifests to run EG.
2. The Gateway API manifests that are supported by the EG release.

This will support
```
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/${ENVOY_GATEWAY_RELEASE_TAG}/gatewayapi-crds.yaml
kubectl apply -f https://github.com/envoyproxy/gateway/releases/download/${ENVOY_GATEWAY_RELEASE_TAG}/install.yaml
```

xref: https://github.com/envoyproxy/gateway/issues/296
xref: https://github.com/envoyproxy/gateway/pull/298
xref: https://github.com/envoyproxy/gateway/issues/297

Signed-off-by: danehans <daneyonhansen@gmail.com>

2022-08-30 23:55 UTC, danehans commented
cc: @arkodg @AliceProxy @Xunzhuo

2022-08-31 00:08 UTC, Xunzhuo submitted a review, later dismissed

2022-08-31 00:19 UTC, arkodg commented on tools/make/kube.mk
> +build-install-yaml:
```suggestion
release-manifests:
```

2022-08-31 00:21 UTC, arkodg commented on tools/hack/build-install-yaml.sh
> +mkdir -p release/
```
mkdir -p release/
curl -sLo release/gatewayapi-crds.yaml https://github.com/kubernetes-sigs/gateway-api/releases/download/${GATEWAY_API_VERSION}/experimental-install.yaml
${KUSTOMIZE} build internal/provider/kubernetes/config/default > release/install.yaml
```
could be moved into the Makefile eliminating the need for another file

2022-08-31 00:23 UTC, danehans commented
@arkodg @Xunzhuo i just remembered that the script for this target needs to replace the "gateway-dev" image with "gateway".

2022-08-31 00:25 UTC, Xunzhuo commented
When releasing an image, we use gateway instead of gateway-dev, right?

2022-08-31 00:32 UTC, arkodg commented
> When releasing an image, we use gateway instead of gateway-dev, right?

Yeah

2022-08-31 00:35 UTC, arkodg commented
from the kubebuilder docs, it looks like it supports the `IMG` env https://book.kubebuilder.io/cronjob-tutorial/running.html, unsure if it works or not with all our mods

2022-08-31 01:05 UTC, Xunzhuo commented
I think if nothing is blocking this PR, we need to merge this first, the release workflow should require this PR.

2022-08-31 01:14 UTC, Xunzhuo commented on tools/make/kube.mk
> +RELEASE_VERSION ?= v0.2.0-rc1
https://github.com/envoyproxy/gateway/blob/main/tools/make/common.mk#L36

2022-08-31 01:21 UTC, danehans commented on tools/make/kube.mk
> +RELEASE_VERSION ?= v0.2.0-rc1
@Xunzhuo thanks for catching this. Commit https://github.com/envoyproxy/gateway/pull/300/commits/f446dd435a0bbe209c6e3218cfcbcd35ff43e8b7 removed the needed RELEASE_VERSION variable.

2022-08-31 01:39 UTC, arkodg approved these changes
thanks for working on this !
I think we can improve the script/rm it in follow up PRs

2022-08-31 01:42 UTC, Xunzhuo approved these changes

2022-08-31 02:00 UTC, LukeShu requested changes
Mostly some shell nits that you're free to ignore for now; but the one change I am insisting on is that `release-manifests` needs to depend on `$(tools/kustomize)`.

Other than that one change, lgtm.

2022-08-31 02:09 UTC, Xunzhuo commented on tools/make/kube.mk
> +release-manifests:
Good catch, I think this is needed.

2022-08-31 15:20 UTC, danehans commented on tools/hack/release-manifests.sh
> +curl -sLo release/gatewayapi-crds.yaml https://github.com/kubernetes-sigs/gateway-api/releases/download/${GATEWAY_API_VERSION}/experimental-install.yaml
https://github.com/envoyproxy/gateway/issues/314 was created to track this issue.

2022-08-31 15:32 UTC, danehans commented on tools/hack/release-manifests.sh
> +}
@LukeShu thanks for the guidance here. I incorporated these suggested changes except for using `|&`:
```
tools/hack/release-manifests.sh: line 16: syntax error near unexpected token `&'
```

2022-08-31 16:03 UTC, merged