Docs contribution
envoyproxy/gateway pull request #3176
Opened 2024-04-11 07:21 UTC by zirain

xref: https://github.com/envoyproxy/gateway/issues/2987

2024-04-11 10:36 UTC, wilsonwu requested changes
Seems it was my mistake for this translation, please help to remove this line.

2024-04-11 10:36 UTC, wilsonwu commented on site/content/zh/_index.md
>  我们在 **GitHub** 通过 [Pull Request](https://github.com/envoyproxy/gateway/pulls) 开启贡献流程。
```suggestion
我们在 **GitHub** 通过 [Pull Request](https://github.com/envoyproxy/gateway/pulls) 开启贡献流程。
```

2024-04-12 02:50 UTC, zirain commented
/retest

2024-04-12 03:48 UTC, Xunzhuo approved these changes
+1 for this, thanks for working on it : )

2024-04-12 04:26 UTC, arkodg approved these changes
LGTM thanks !
feels good to delete lines, doesnt it ?

2024-04-12 04:26 UTC, merged

2024-04-12 04:28 UTC, zirain commented
> LGTM thanks ! feels good to delete lines, doesnt it ?

next is the `releases` folder, haha!