feat: support custom names for generated k8s resources
envoyproxy/gateway pull request #3537
Opened 2024-06-04 22:45 UTC by arkodg

Relates to https://github.com/envoyproxy/gateway/pull/3527

2024-06-05 11:08 UTC, cnvergence requested changes
probably we would need to also change it in kubernetes provider
https://github.com/envoyproxy/gateway/blob/607d8bcd9a833841eee057b263c0bdc06de0fbea/internal/provider/kubernetes/helpers.go#L151

2024-06-05 17:48 UTC, arkodg commented
hey @cnvergence can you elaborate why thats needed, the above diff is changing the value right before setting the resource name ?

2024-06-05 20:44 UTC, arkodg commented
oh @cnvergence I see the issue now, we are fetching based on name and not labels 😢 
https://github.com/envoyproxy/gateway/blob/cdd4e065d4a2a5e3657052664073972f06ac77dd/internal/provider/kubernetes/predicates.go#L467
&
https://github.com/envoyproxy/gateway/blob/cdd4e065d4a2a5e3657052664073972f06ac77dd/internal/provider/kubernetes/predicates.go#L483

cc @dprotaso this is the issue seen in https://github.com/knative-extensions/net-gateway-api/pull/738

2024-06-06 08:12 UTC, cnvergence commented on internal/gatewayapi/helpers.go
> +func OwnerLabels(gateway *gwapiv1.Gateway, mergeGateways bool) map[string]string {
🚀

2024-06-06 08:17 UTC, cnvergence approved these changes
LGTM

2024-06-06 14:35 UTC, davem-git commented
If this is addressed here, will it also fix when I rename the `envoyDeployment`:, the HPA `envoyHpa`? It no longer works it keeps the original generated name. There doesn't seem to be a way to patch that either

2024-06-06 23:25 UTC, arkodg commented
> If this is addressed here, will it also fix when I rename the `envoyDeployment`:, the HPA `envoyHpa`? It no longer works it keeps the original generated name. There doesn't seem to be a way to patch that either

thanks for catching this ! ive fixed the deployment targetRef naming in hpa.
I havent changed the name on the hpa resource itself, that needs an API change, which can be handled in a future PR

2024-06-06 23:36 UTC, zhaohuabing reviewed
🚀

2024-06-06 23:37 UTC, zhaohuabing reviewed
🚀

2024-06-06 23:38 UTC, zhaohuabing approved these changes

2024-06-07 00:00 UTC, merged

2024-06-14 15:27 UTC, davem-git commented
On this same issue. I've renamed the deployment by patching the name, this causes the gateway to break. While the deployment with 3 replicas I get this error 

```sh
  Last Transition Time:  2024-06-14T15:02:58Z
    Message:               The Gateway has been scheduled by Envoy Gateway
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2024-06-14T15:03:07Z
    Message:               Deployment replicas unavailable
    Observed Generation:   1
    Reason:                NoResources
    Status:                False
    Type:                  Programmed
```

the gateway status is this 

```sh
NAME            CLASS           ADDRESS         PROGRAMMED   AGE
acme-envoy   acme-envoy   IPADDRESS   False        4m19s
```

2024-06-14 16:18 UTC, arkodg commented
@davem-git can you raise a separate GH issue to highlight the issue you are facing