document workaround for conformance tests on Mac
envoyproxy/gateway pull request #372
Opened 2022-09-09 19:10 UTC by arkodg

Relates to https://github.com/envoyproxy/gateway/issues/284

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

2022-09-09 19:12 UTC, arkodg commented
https://github.com/envoyproxy/gateway/issues/323 will be needed to replace the local manifest to point to a custom image rather than `envoyproxy/gateway-dev:latest`

2022-10-03 18:24 UTC, AliceProxy approved these changes
lgtm. I've been doing using Kubernetes clusters and doing this for development so should be a fine workaround.

2022-10-03 18:47 UTC, danehans requested changes

2022-10-03 18:47 UTC, danehans commented on DEVELOPER.md
> +and run the Gateway API conformance tests.
s/run/runs/

2022-10-03 18:47 UTC, danehans commented on DEVELOPER.md
> +
Unneeded extra line added. Please remove.

2022-10-03 21:40 UTC, danehans approved these changes

2022-10-03 21:47 UTC, merged