feat: support user-facing version
envoyproxy/gateway pull request #609
Opened 2022-10-19 04:58 UTC by Xunzhuo

Resolves: https://github.com/envoyproxy/gateway/issues/498

<img width="844" alt="image" src="https://user-images.githubusercontent.com/48784001/196601303-4550a6a9-6b89-4166-906e-98322da5641f.png">

Signed-off-by: bitliu <bitliu@tencent.com>

2022-10-19 15:32 UTC, danehans requested changes
Looks like you have stale quickstart-related changes that should be removed from this PR.

2022-10-19 15:32 UTC, danehans commented on docs/conf.py
> +copyright = '2022 Envoy Gateway Project Authors | ' + version
Let's drop the year from the copyright.

xref: https://github.com/envoyproxy/gateway/pull/590/files

2022-10-19 15:32 UTC, danehans commented on README.md
> +* [Roadmap](./docs/design/roadmap.md)
These have already been updated: https://raw.githubusercontent.com/envoyproxy/gateway/main/README.md

2022-10-19 15:35 UTC, danehans commented
IMHO having too many options can cause confusion. I prefer `envoy-gateway version` and the output is the EG, Gateway API, Envoy versions and commit SHA.

2022-10-19 15:51 UTC, AliceProxy commented
> 

Plus one on keeping it simple. For example, you can `go version` but not also `go --version` so there is an established pattern for only supporting one style.

2022-10-19 16:04 UTC, Xunzhuo commented
Yes I am intending to just keep `eg version`.

2022-10-19 16:15 UTC, Xunzhuo commented
I have removed the --version for syncing the style.

2022-10-19 18:56 UTC, arkodg commented
> IMHO having too many options can cause confusion. I prefer `envoy-gateway version` and the output is the EG, Gateway API, Envoy versions, and the commit SHA.
> 
> Thoughts @arkodg @youngnick @skriss @LukeShu @AliceProxy

+ 1 on a single pattern, either `envoy-gateway version` or `envoy-gateway --version`
dont have a strong opinion on either

2022-10-19 19:12 UTC, Xunzhuo reviewed
/wait 

I am not sure and not recomment to put this into v0.2.0, I think a couple of things need more discussion.

2022-10-19 20:44 UTC, danehans commented
> /wait
I am not sure and not recomment to put this into v0.2.0, I think a couple of things need more discussion.

@Xunzhuo converted to draft in the meantime.

2022-11-03 15:55 UTC, danehans approved these changes

2022-11-03 16:38 UTC, merged