add -e to echo command
envoyproxy/gateway pull request #741
Opened 2022-11-21 13:45 UTC by thredreams

To solve the problem of invalid escape characters, add the - e option to the echo command in the ". mk" files in the gateway/tool/make directory

2022-11-21 13:55 UTC, Xunzhuo commented
Plz sign your commit first, and describe the details of the issue you pointed out.

2022-11-22 04:05 UTC, Xunzhuo commented on tools/make/common.mk
>  	@echo "Envoy Gateway is an open source project for managing Envoy Proxy as a standalone or Kubernetes-based application gateway\n"
Add -e to here too.

2022-11-22 04:07 UTC, Xunzhuo requested changes
You need to add `SHELL=/bin/bash` to common.mk, to specify the shell which makefile is using.

2022-11-22 04:20 UTC, thredreams commented
> You need to add `SHELL=/bin/bash` to common.mk, to specify the shell which makefile is using.
> 
> Others LGTM. Thank you @thredreams.

In fact, I didn't do this at the beginning because I was worried about whether there were some commands in the file that should not be executed in bash

2022-11-22 04:21 UTC, Xunzhuo commented
> In fact, I didn't do this at the beginning because I was worried about whether there were some commands in the file that should not be executed in bash

Not for now : )

2022-11-22 04:27 UTC, Xunzhuo commented
Thanks @thredreams, after CI passed, I am going to merge this.

2022-11-22 04:32 UTC, merged