infra: support custom base image
envoyproxy/gateway pull request #749
Opened 2022-11-24 12:03 UTC by zirain

Signed-off-by: hejianpeng <hejianpeng2@huawei.com>

fixes: https://github.com/envoyproxy/gateway/issues/327

this PR make folks can custom base image for better debugging by running following command:
```console
IMAGE_BASE=<your_base_image:-ubuntu:jammy> make kube-install-image
```

2022-11-29 15:56 UTC, danehans requested changes
FYI from https://github.com/envoyproxy/gateway/issues/327#issuecomment-1233643635, a command is desired for #327 to be closed.

cc: @arkodg

2022-11-30 01:00 UTC, zirain commented
`collect` is not enough, dev users also need change logging level on the fly by `logging`, or check stats from `/stats`
BTW, `envoy-gateway` need a long way to go.

2022-11-30 22:32 UTC, danehans commented
I would like to get input from @arkodg before merging this PR due to https://github.com/envoyproxy/gateway/issues/327#issuecomment-1233643635.

2022-12-05 18:08 UTC, arkodg commented
since the goal is to improve debuggablity, would prefer EG provided commands, reports directly instead of the user swapping out the container image to something that contains more utility commands in it

2022-12-05 20:47 UTC, danehans commented
@zirain is https://github.com/envoyproxy/gateway/pull/749#issuecomment-1337876893 something you can take on? It would be a big help to the project.

2022-12-07 21:28 UTC, arkodg commented
> I do not think it's a good idea to provider feature on `eg`, maybe a tools call `egctl`?

yeah `egctl` makes a lot of sense here, which can be the entry point to  `analyze` / `report` / `collect` subcmd ?

2022-12-08 00:44 UTC, zirain commented
> > I do not think it's a good idea to provider feature on `eg`, maybe a tools call `egctl`?
> 
> yeah `egctl` makes a lot of sense here, which can be the entry point to `analyze` / `report` / `collect` subcmd ?

yes, that's what I think.

2022-12-09 02:31 UTC, zirain commented
@danehans @arkodg let's close this first, then I will raise a proposal about new binary named `egctl`, WDYT?

2022-12-09 17:38 UTC, arkodg commented
> @danehans @arkodg let's close this first, then I will raise a proposal about new binary named `egctl`, WDYT?

sounds good, thanks !

2022-12-10 01:29 UTC, zirain commented
close this for https://github.com/envoyproxy/gateway/issues/794

2022-12-10 01:29 UTC, closed without merging