release: add v0.3.0-rc.1 release notes
envoyproxy/gateway pull request #961
Opened 2023-02-02 13:03 UTC by Xunzhuo

Signed-off-by: bitliu <bitliu@tencent.com>

2023-02-02 16:35 UTC, danehans commented on release-notes/v0.3.0-rc1.yaml
> +      Fixes Wait for Job Succeeded before conformance est
s/est/test/

2023-02-02 16:37 UTC, danehans reviewed
I found 1 typo, otherwise LGTM.

2023-02-02 20:23 UTC, danehans commented
@Xunzhuo please add https://github.com/envoyproxy/gateway/issues/950 as a release note for GRPCRoute support.

cc: @arkodg

2023-02-03 01:36 UTC, zirain reviewed
lgtm, thanks!

2023-02-03 02:28 UTC, danehans submitted a review, later dismissed

2023-02-03 02:52 UTC, danehans requested changes

2023-02-03 02:52 UTC, danehans commented on VERSION
> +v0.3.0-rc.1
`VERSION` should not be manually updated. It gets updated with `make docs-release TAG=v${MAJOR_VERSION}.${MINOR_VERSION}` which should only be run for releases and not release candidates.

2023-02-03 03:04 UTC, danehans commented on VERSION
> +v0.3.0-rc.1
VERSION needs to be updated so the version command reflects the proper version.

2023-02-03 03:04 UTC, danehans approved these changes

2023-02-03 03:04 UTC, merged